### ISSUE TITLE
crop이나 화면 로테이션 시 변경된 실제 이미지의 크기로 조정이되어야 합니다.

### ISSUE THREAD

**Issue by kim-jeongki** [nhnent/tui.component.image-editor#10]
예전에 가이드 주신 내용으로는 처음에 이미지를 로딩 후 image-editor wrapper 에 height값을 설정하게 되어 있는데요.
문제는 crop이나 화면 로테이션 시 실제 이미지 크기가 변경됨에도 불구하고 원래 크기의 영역이 공허하게 뜨는 문제가 발생되고 있습니다.

켄버스에 렌더링된 크기를 정확히 반영할 수 있는 방법이 필요합니다.

**Comment by seonim-ryu** [comment]
[#12](https://github.com/nhnent/tui.component.image-editor/issues/12) 동일 이슈로 이슈 클로징합니다.

**Comment by seonim-ryu** [comment]
현재 이미지 에디터에서 편집 후 이미지 사이즈가 변경되는 경우는 `crop`과 `rotation`에 해당되며,
동적으로 이미지 에디터의 사이즈를 조정하는 경우 각 액션 이후에 실행되는 이벤트에서
다음과 같은 방식으로 이미지 에디터와 관련된 엘리먼트 정보를 가져와 처리할 수 있습니다.
(하단 예제 참조, 편의를 위해 `jQuery` 사용)

이전 버전의 경우 `endCropping` 발생 시점에서 크롭된 이미지의 사이즈를 가져오지 못하는 이슈가 있어 이 부분이 개선된 상태입니다.

```js
var resizeEditor = function() {
    var $editor = $('.tui-image-editor');
    var $container = $('.tui-image-editor-canvas-container');
    var height = parseFloat($container.css('max-height'));

    $editor.height(height);
};

imageEditor.on({
    endCropping: function() { // crop 후 발생
        resizeEditor();
    },
    ...
});
```
