### ISSUE TITLE
모바일 샘플에서의 텍스트 입력을 하다보면 텍스트박스의 위치가 이동되면서 깜빡이는 현상이 발생합니다.

### ISSUE THREAD

**Issue by kim-jeongki** [nhnent/tui.component.image-editor#11]

**Comment by seonim-ryu** [comment]
텍스트 입력 상자는 기능 개선 중에 있으며, 다음 버전 배포 시 적용될 예정입니다.

**Comment by seonim-ryu** [comment]
`1.3.0` 버전에서 해당 이슈 및 텍스트 입력 시 기준점(`(center, center) -> (left, top)`이 변경되어 적용되었습니다.
