### ISSUE TITLE
브라우저 크기에 따라 캔버스의 크기가 재조정되어야 합니다.

### ISSUE THREAD

**Issue by kim-jeongki** [nhnent/tui.component.image-editor#12]
기존 div.image-wrapper와 canvas의 높이와 넓이가 고정될경우 
사용자의 환경 및 viewport 크기에 따라 화면 노출이 잘리거나 과다하게 작은 영역만 표시되어 불편함이 초래될 수 있을 듯 합니다.
특정 scale의 factor로 zoom In out 을 처리해주는 기능이 필요할 듯 합니다.
window.resize에 대한 처리는 외부에서 하는 게 좋을 것 같구요

**Comment by seonim-ryu** [comment]
API 추가 여부를 검토하고 있으며, 서비스단에서 처리할 수 있는 경우 가이드 드리도록 하겠습니다.

**Comment by seonim-ryu** [comment]
`resizeCanvasDimension()` API가 추가되었으며 API 문서 참조바랍니다.
