### ISSUE TITLE
Can't add shape after crop

### ISSUE THREAD

**Issue by SmboBeast** [nhnent/tui.component.image-editor#14]
Hi there,

Great code here by the way.  Just wanted to let you know that after cropping, I can't add a shape to the canvas.

Thanks

**Comment by seonim-ryu** [comment]
Thanks for using our component. :)

I confirm issue that you mentioned, but i don’t reappear.
Did you see a problem with the sample page?
Could you explain more detail to me?

The image below shows when I draw the shape after cropping.

![issue](https://cloud.githubusercontent.com/assets/18183560/21166762/e3902f40-c1ea-11e6-8f21-1c6e838241bf.gif)

**Comment by SmboBeast** [comment]
You know, I tried it 10 times, and I could only reproduce it twice.  It was
some sort of weird combination of rotating and then trying to draw a shape,
after cropping.  But I can't replicate it again.  If I can, I will respond
again.

Thanks
