### ISSUE TITLE
여러개의 TextObject를 선택하면서 changeTextStyle 호출되면 styles 정보가 초기화 되는 현상이 발생합니다.

### ISSUE THREAD

**Issue by kim-jeongki** [nhnent/tui.component.image-editor#7]

**Comment by kim-jeongki** [comment]
여러개의 TextObject를 생성 후 선택한 TextObject에 대한 styles을 우측의 상세 옵션에 적용하기 위해 값을 동기화하다고 보면 fontSize와 같은 style이 제대로 설정되었음에도 기존 스타일이 날아가는 문제가 발생하고 있습니다.

**Comment by seonim-ryu** [comment]
[#5](https://github.com/nhnent/tui.component.image-editor/issues/5) 동일 이슈
