### ISSUE TITLE
TextObject 선택 시 무조건 텍스트 추가 모드로 전환됩니다.

### ISSUE THREAD

**Issue by kim-jeongki** [nhnent/tui.component.image-editor#9]

**Comment by seonim-ryu** [comment]
텍스트 오브젝트 선택 후 더블 클릭 시 텍스트 추가 모드로 전환되도록 수정되었으며,
아이콘 또는 라인 오브젝트 선택 후 해당 모드로 넘어가는 기능은 다음 버전 적용 여부를 검토중입니다.
